'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import QRCodeStudio from '@/components/qr/QRCodeStudio';
import BarcodeStudio from '@/components/barcode/BarcodeStudio';
import { BLOG_POSTS } from '@/lib/blog-data';
import {
  QrCode,
  Barcode,
  ShieldCheck,
  Zap,
  Download,
  Palette,
  CheckCircle2,
  Sparkles,
  ArrowRight,
  ChevronDown,
  Store,
  Utensils,
  Package,
  Layers,
  HelpCircle,
  ExternalLink,
} from 'lucide-react';

export default function HomePage() {
  const [activeStudioTab, setActiveStudioTab] = useState<'qr' | 'barcode'>('qr');
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const faqs = [
    {
      q: 'Are the generated QR codes and barcodes 100% free for commercial use?',
      a: 'Yes, completely free. You can use codes generated by QR Suite on physical product packaging, billboard advertisements, restaurant table tents, marketing flyers, books, and digital media with zero royalties, zero attribution requirements, and zero expiration dates.',
    },
    {
      q: 'Do QR Suite QR codes ever expire or have scan limits?',
      a: 'Never. QR Suite creates standard static QR codes where the destination URL or data is encoded directly into the pixel pattern. Because there is no middleman redirect server, your QR codes will work indefinitely for as long as your destination website or Wi-Fi network exists.',
    },
    {
      q: 'Is my data private when generating Wi-Fi or contact (vCard) codes?',
      a: 'Yes, 100%. All QR code calculations, image rendering, and barcode syntheses occur entirely inside your browser using client-side JavaScript. Your Wi-Fi passwords, personal phone numbers, and customer URLs are never transmitted to our servers or saved in any database.',
    },
    {
      q: 'What resolution should I download for professional printing?',
      a: 'For business cards, flyers, and merchandise, we strongly recommend downloading the Vector SVG format, which provides mathematical infinite scalability for commercial print shops (such as Adobe Illustrator, InDesign, or vector cutters). If using PNG, select our "Print 2400px" option to ensure crisp, blur-free reproduction.',
    },
    {
      q: 'Can I add my business logo without breaking scannability?',
      a: 'Yes. QR Suite automatically applies High (Level H) Reed-Solomon Error Correction whenever you enable a logo overlay. Level H allows smartphones to reliably reconstruct the data even if up to 30% of the code center is obscured by your logo badge.',
    },
  ];

  return (
    <div className="space-y-16 sm:space-y-24 pb-20">
      {/* Hero Section with Live Studio */}
      <section className="relative overflow-hidden pt-8 sm:pt-14 pb-4">
        {/* Subtle background gradient glow */}
        <div className="absolute top-0 inset-x-0 h-96 bg-gradient-to-b from-indigo-50/70 via-slate-50/40 to-transparent -z-10 pointer-events-none" />

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-8 sm:mb-12 space-y-4">
            {/* Pill Badge */}
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-indigo-50 text-indigo-700 border border-indigo-200/80 shadow-2xs">
              <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
              <span>Free Forever • 100% Client-Side Private • No Watermarks</span>
            </div>

            <h1 className="text-3xl sm:text-5xl font-extrabold text-slate-900 tracking-tight leading-tight">
              Professional QR & Barcode Generator for Small Business
            </h1>

            <p className="text-base sm:text-lg text-slate-600 leading-relaxed max-w-2xl mx-auto">
              Create branded QR codes with custom logos, colors, and Wi-Fi presets, plus retail-standard Code 128 and EAN-13 barcodes. Download instantly in lossless SVG and high-res PNG.
            </p>
          </div>

          {/* Studio Switcher Buttons */}
          <div className="flex justify-center mb-6">
            <div className="inline-flex p-1.5 bg-slate-200/70 rounded-2xl border border-slate-300/80 shadow-2xs">
              <button
                type="button"
                id="hero-tab-qr"
                onClick={() => setActiveStudioTab('qr')}
                className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold transition-all ${
                  activeStudioTab === 'qr'
                    ? 'bg-white text-indigo-600 shadow-sm'
                    : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                <QrCode className="w-4 h-4" />
                <span>QR Code Generator & Customizer</span>
              </button>

              <button
                type="button"
                id="hero-tab-barcode"
                onClick={() => setActiveStudioTab('barcode')}
                className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold transition-all ${
                  activeStudioTab === 'barcode'
                    ? 'bg-white text-indigo-600 shadow-sm'
                    : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                <Barcode className="w-4 h-4" />
                <span>Barcode Studio (Code 128 / EAN)</span>
              </button>
            </div>
          </div>

          {/* Interactive Studio Workspace */}
          <div className="max-w-5xl mx-auto">
            {activeStudioTab === 'qr' ? (
              <QRCodeStudio initialType="url" />
            ) : (
              <BarcodeStudio initialFormat="CODE128" />
            )}
          </div>
        </div>
      </section>

      {/* Feature Highlights Grid */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-2xl mx-auto mb-12 space-y-2">
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 tracking-tight">
            Engineered for Flawless Real-World Scannability
          </h2>
          <p className="text-sm sm:text-base text-slate-600">
            Everything your business needs to turn physical foot traffic into repeat digital customers.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div className="bg-white p-6 rounded-2xl border border-slate-200/90 shadow-2xs hover:shadow-md transition">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center mb-4">
              <Download className="w-5 h-5" />
            </div>
            <h3 className="text-base font-bold text-slate-900 mb-1.5">Lossless Vector SVG & 2400px PNG</h3>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              Export pixel-perfect vector SVG files ready for commercial signage, decals, and packaging printers, or grab ultra-HD raster PNGs.
            </p>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-slate-200/90 shadow-2xs hover:shadow-md transition">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center mb-4">
              <Palette className="w-5 h-5" />
            </div>
            <h3 className="text-base font-bold text-slate-900 mb-1.5">Custom Colors & Center Logo</h3>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              Match your brand palette with hex values, quiet-zone sliders, and upload your company monogram or choose high-converting preset badges.
            </p>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-slate-200/90 shadow-2xs hover:shadow-md transition">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center mb-4">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <h3 className="text-base font-bold text-slate-900 mb-1.5">100% Client-Side Privacy</h3>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              Your Wi-Fi passwords, contact details, and links never leave your device. All rendering is executed directly in your browser.
            </p>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-slate-200/90 shadow-2xs hover:shadow-md transition">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center mb-4">
              <Barcode className="w-5 h-5" />
            </div>
            <h3 className="text-base font-bold text-slate-900 mb-1.5">Standard Retail & Warehouse Barcodes</h3>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              Generate GS1-compliant EAN-13 barcodes for retail stores, UPC-A for US groceries, and Code 128 for inventory and parcel tracking.
            </p>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-slate-200/90 shadow-2xs hover:shadow-md transition">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center mb-4">
              <Zap className="w-5 h-5" />
            </div>
            <h3 className="text-base font-bold text-slate-900 mb-1.5">Zero Expirations & Static Freedom</h3>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              Never get locked into scam subscriptions where your printed posters break after 14 days. Our static codes last forever.
            </p>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-slate-200/90 shadow-2xs hover:shadow-md transition">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center mb-4">
              <CheckCircle2 className="w-5 h-5" />
            </div>
            <h3 className="text-base font-bold text-slate-900 mb-1.5">High Error Correction (Level H)</h3>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              Industry-grade Reed-Solomon math allows codes to be successfully decoded even when 30% damaged, scratched, or covered by a logo.
            </p>
          </div>
        </div>
      </section>

      {/* Small Business Use-Cases */}
      <section className="bg-slate-100/70 py-16 border-y border-slate-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto mb-12 space-y-2">
            <span className="text-xs font-bold text-indigo-600 uppercase tracking-wider">
              Real-World Applications
            </span>
            <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 tracking-tight">
              How Small Businesses Use QR Suite
            </h2>
            <p className="text-sm text-slate-600">
              Practical, high-converting touchpoints tested across thousands of physical locations.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-2xs space-y-3">
              <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center">
                <Utensils className="w-5 h-5" />
              </div>
              <h3 className="text-lg font-bold text-slate-900">Cafes & Dining</h3>
              <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
                Place Wi-Fi QR codes on table tents so guests connect with one tap without bothering baristas. Add Google Review standees at checkout.
              </p>
              <ul className="text-xs text-slate-500 space-y-1.5 pt-2 border-t border-slate-100">
                <li className="flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                  <span>Drink coaster seasonal tap lists</span>
                </li>
                <li className="flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                  <span>One-tap WPA3 guest Wi-Fi connect</span>
                </li>
              </ul>
            </div>

            <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-2xs space-y-3">
              <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center">
                <Store className="w-5 h-5" />
              </div>
              <h3 className="text-lg font-bold text-slate-900">Retail & Boutiques</h3>
              <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
                Generate EAN-13 barcodes for product packaging shelves, plus QR codes on hang-tags linking to sizing guides or artisan origin videos.
              </p>
              <ul className="text-xs text-slate-500 space-y-1.5 pt-2 border-t border-slate-100">
                <li className="flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-indigo-600" />
                  <span>Retail checkout-compatible EAN-13</span>
                </li>
                <li className="flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-indigo-600" />
                  <span>Customer loyalty program QR signups</span>
                </li>
              </ul>
            </div>

            <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-2xs space-y-3">
              <div className="w-10 h-10 rounded-xl bg-violet-50 text-violet-600 flex items-center justify-center">
                <Package className="w-5 h-5" />
              </div>
              <h3 className="text-lg font-bold text-slate-900">Warehouse & Services</h3>
              <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
                Encode bin inventory with Code 128 barcodes and print digital vCard QR codes on technician business cards for instant contact saving.
              </p>
              <ul className="text-xs text-slate-500 space-y-1.5 pt-2 border-t border-slate-100">
                <li className="flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-violet-600" />
                  <span>High-density Code 128 inventory tags</span>
                </li>
                <li className="flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-violet-600" />
                  <span>Instant address book vCard import</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* 3 Step Workflow */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-xl mx-auto mb-12 space-y-2">
          <span className="text-xs font-bold text-indigo-600 uppercase tracking-wider">Fast & Frictionless</span>
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 tracking-tight">
            How It Works in 3 Simple Steps
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative">
          <div className="bg-white p-6 rounded-2xl border border-slate-200 text-center space-y-3">
            <div className="w-12 h-12 rounded-2xl bg-indigo-600 text-white font-bold text-lg flex items-center justify-center mx-auto shadow-sm">
              1
            </div>
            <h3 className="text-base font-bold text-slate-900">Choose Type & Enter Data</h3>
            <p className="text-xs sm:text-sm text-slate-600">
              Select URL, Wi-Fi, vCard, Code 128, or EAN-13. Input your details with real-time format validation.
            </p>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-slate-200 text-center space-y-3">
            <div className="w-12 h-12 rounded-2xl bg-indigo-600 text-white font-bold text-lg flex items-center justify-center mx-auto shadow-sm">
              2
            </div>
            <h3 className="text-base font-bold text-slate-900">Customize Colors & Logo</h3>
            <p className="text-xs sm:text-sm text-slate-600">
              Pick brand-matching colors, adjust quiet zones, and place your logo with automatic High Error Correction.
            </p>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-slate-200 text-center space-y-3">
            <div className="w-12 h-12 rounded-2xl bg-indigo-600 text-white font-bold text-lg flex items-center justify-center mx-auto shadow-sm">
              3
            </div>
            <h3 className="text-base font-bold text-slate-900">Download & Print Instantly</h3>
            <p className="text-xs sm:text-sm text-slate-600">
              Grab vector SVG for print shops or ultra-res 2400px PNG. Test scannability directly with your phone.
            </p>
          </div>
        </div>
      </section>

      {/* Featured Blog & Guides Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col sm:flex-row items-start sm:items-end justify-between mb-8 gap-4">
          <div>
            <span className="text-xs font-bold text-indigo-600 uppercase tracking-wider">
              Educational Guides
            </span>
            <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 tracking-tight">
              Small Business Guides & Best Practices
            </h2>
            <p className="text-sm text-slate-600 mt-1">
              Field-tested strategies on sizing, scannability, retail standards, and conversion.
            </p>
          </div>
          <Link
            href="/blog"
            className="text-sm font-semibold text-indigo-600 hover:text-indigo-800 flex items-center gap-1.5 transition shrink-0"
          >
            <span>View All 3 Guides</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {BLOG_POSTS.map((post) => (
            <article
              key={post.slug}
              className="bg-white rounded-2xl border border-slate-200/90 shadow-2xs hover:shadow-md transition flex flex-col justify-between overflow-hidden group"
            >
              <div className="p-6 space-y-3">
                <div className="flex items-center justify-between text-xs text-slate-500">
                  <span className="px-2.5 py-0.5 rounded-full font-semibold bg-indigo-50 text-indigo-700">
                    {post.category}
                  </span>
                  <span>{post.readTime}</span>
                </div>

                <Link href={`/blog/${post.slug}`} className="block">
                  <h3 className="text-base font-bold text-slate-900 group-hover:text-indigo-600 transition-colors leading-snug">
                    {post.title}
                  </h3>
                </Link>

                <p className="text-xs sm:text-sm text-slate-600 line-clamp-3 leading-relaxed">
                  {post.excerpt}
                </p>
              </div>

              <div className="px-6 py-4 bg-slate-50/70 border-t border-slate-100 flex items-center justify-between text-xs">
                <span className="font-medium text-slate-600">By {post.author.name}</span>
                <Link
                  href={`/blog/${post.slug}`}
                  className="font-semibold text-indigo-600 group-hover:translate-x-0.5 transition-transform flex items-center gap-1"
                >
                  <span>Read Guide</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </article>
          ))}
        </div>
      </section>

      {/* Frequently Asked Questions */}
      <section className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-8 space-y-2">
          <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 tracking-tight">
            Frequently Asked Questions
          </h2>
          <p className="text-sm text-slate-600">
            Clear, honest answers about commercial usage, privacy, and printing.
          </p>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, index) => {
            const isOpen = openFaq === index;
            return (
              <div
                key={faq.q}
                className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-2xs transition"
              >
                <button
                  type="button"
                  onClick={() => setOpenFaq(isOpen ? null : index)}
                  className="w-full text-left px-5 py-4 flex items-center justify-between gap-4 font-semibold text-sm sm:text-base text-slate-900 hover:text-indigo-600"
                >
                  <span>{faq.q}</span>
                  <ChevronDown
                    className={`w-4 h-4 text-slate-400 shrink-0 transition-transform duration-200 ${
                      isOpen ? 'rotate-180 text-indigo-600' : ''
                    }`}
                  />
                </button>
                {isOpen && (
                  <div className="px-5 pb-5 pt-1 text-xs sm:text-sm text-slate-600 leading-relaxed border-t border-slate-100">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* Bottom CTA Banner */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-gradient-to-r from-indigo-900 via-indigo-800 to-violet-900 rounded-3xl p-8 sm:p-12 text-white text-center sm:text-left flex flex-col sm:flex-row items-center justify-between gap-8 shadow-md">
          <div className="space-y-2 max-w-xl">
            <h2 className="text-2xl sm:text-3xl font-extrabold tracking-tight">
              Ready to generate print-ready codes for your business?
            </h2>
            <p className="text-indigo-200 text-sm sm:text-base">
              Start creating vector QR codes and barcodes with zero signup, zero watermarks, and 100% client-side privacy.
            </p>
          </div>
          <div className="flex flex-col sm:flex-row gap-3 shrink-0">
            <Link
              href="/tools/qr-generator"
              className="px-6 py-3.5 bg-white text-indigo-900 hover:bg-indigo-50 font-bold text-sm rounded-xl transition shadow-sm text-center"
            >
              Launch QR Studio
            </Link>
            <Link
              href="/tools/barcode-generator"
              className="px-6 py-3.5 bg-indigo-700/80 hover:bg-indigo-700 border border-indigo-500 text-white font-bold text-sm rounded-xl transition text-center"
            >
              Barcode Studio
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
